// import React from "react";
// import Head from "next/head";

// const about = () => {
//   return (
//     <div>
//       <Head>
//         <title>About Page</title>
//         <meta
//           name="description"
//           content="About Page Generated by create ylmgrbz"
//         />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       about
//     </div>
//   );
// };

// export default about;
