import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Intro from "../components/Intro";
import Services from "../components/Services";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Personal/Agency Website</title>
        <meta name="description" content="Generated by create ylmgrbz" />
      </Head>
      <Intro />
      <Services />
    </div>
  );
}
